CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    alias VARCHAR(16) NOT NULL UNIQUE,
    original_url TEXT NOT NULL,
    clicks INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_urls_alias ON urls(alias);